M48
; DRILL file {KiCad 7.0.11-1-dev-0f715223e9} date Thu 18 Jan 2024 09:50:58 AM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-18T09:50:58-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-1-dev-0f715223e9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X2.7747Y-1.0708
X2.7747Y-1.248
M30
